server:
  port: 8090
  servlet:
    context-path: /
  ssl:
    key-store-password: fwagueti
    key-store-type: JKS
    key-store: classpath:looking.cool.jks

spring:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # >dev
    url: jdbc:mysql://localhost:3310/linkup?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    # >qa
    # url: jdbc:mysql://looking.cool:3310/linkup?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
  level:
    com.zaxxer.hikari: DEBUG
    com.alibaba.druid: DEBUG
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG


